name: hiwiki
label: Hindi Wikipedia
host: hi.wikipedia.org

external_samples:
  sampled_revisions.10k_2020:
    quarry_url: https://quarry.wmflabs.org/run/467016/output/0/json-lines
    quarry_page: https://quarry.wmflabs.org/query/44835

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - sysop
   - oversight
   - bot
   - rollbacker
   - checkuser
   - abusefilter
   - bureaucrat
   - autopatrolled
   - autoreview
   - reviewer
  labeled_samples:
    autolabeled_revisions.10k_2020: sampled_revisions.10k_2020
