name: ukwiki
label: Ukranian Wikipedia
host: uk.wikipedia.org

external_samples:
  sampled_revisions.20k_2015:
    quarry_url: http://quarry.wmflabs.org/run/48597/output/0/json-lines?download=true
  human_labeled_revisions.5k_2015:
    labeling_campaign: https://labels.wmflabs.org/campaigns/ukwiki/11/

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - abusefilter
   - arbcom
   - bureaucrat
   - checkuser
   - rollbacker
   - sysop
   - bot
  labeled_samples:
    autolabeled_revisions.20k_2015: sampled_revisions.20k_2015

merged_samples:
  labeled_revisions.20k_2015:
    - human_labeled_revisions.5k_2015
    - autolabeled_revisions.20k_2015

extracted_samples:
  labeled_revisions.w_cache.20k_2015:
    sample: labeled_revisions.20k_2015
    features_for:
      - damaging
      - goodfaith

models:
  damaging:
    observations: labeled_revisions.w_cache.20k_2015
    label: damaging
    pop_rate_true: 0.022485268272511114
    tune: true
    cv_train:
      algorithm: GradientBoosting
      build_number: 1
      parameters:
        learning_rate: 0.01
        max_depth: 5
        max_features: log2
        n_estimators: 700
  goodfaith:
    observations: labeled_revisions.w_cache.20k_2015
    label: goodfaith
    pop_rate_true: 0.9853199627830043
    tune: true
    cv_train:
      algorithm: GradientBoosting
      build_number: 1
      parameters:
        learning_rate: 0.01
        max_depth: 5
        max_features: log2
        n_estimators: 700
